# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LeanMassUp' do

  # pod 'React', :path => '../node_modules/react-native', :subspecs => [
  #   'Core',
  #   'CxxBridge',
  #   'DevSupport',
  #   # the following ones are the ones taken from "Libraries" in Xcode:
  #   'RCTAnimation',
  #   'RCTActionSheet',
  #   'RCTBlob',
  #   'RCTGeolocation',
  #   'RCTImage',
  #   'RCTLinkingIOS',
  #   'RCTNetwork',
  #   'RCTSettings',
  #   'RCTText',
  #   'RCTVibration',
  #   'RCTWebSocket'
  # ]
 
  # the following dependencies are dependencies of React native itself.
  # pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/Yoga.podspec'
  # pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  # pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  # pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/GLog.podspec'
  

  pod 'Firebase/Core'


  # pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'Bolts'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKCoreKit'
  # pod 'FacebookSDK'

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end
