# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'LeanMassUp' do

  pod 'Firebase/Core'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
